### ISSUE TITLE
rails db:migrateで以下のエラーが出る

### ISSUE THREAD

**Issue by RenFukatsu** [bana118/hack-us-server#20]
```
root@740ce87ebe47:/workspaces/hack-us-server# rails db:migrate
== 20210618033458 AddUidUniqueIndexToUsers: migrating =========================
-- add_index(:users, :uid, {:unique=>true})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate entry '' for key 'index_users_on_uid'
/workspaces/hack-us-server/db/migrate/20210618033458_add_uid_unique_index_to_users.rb:5:in `change'
/workspaces/hack-us-server/bin/rails:7:in `<top (required)>'
/workspaces/hack-us-server/bin/spring:12:in `block in <top (required)>'
/workspaces/hack-us-server/bin/spring:9:in `<top (required)>'

Caused by:
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '' for key 'index_users_on_uid'
/workspaces/hack-us-server/db/migrate/20210618033458_add_uid_unique_index_to_users.rb:5:in `change'
/workspaces/hack-us-server/bin/rails:7:in `<top (required)>'
/workspaces/hack-us-server/bin/spring:12:in `block in <top (required)>'
/workspaces/hack-us-server/bin/spring:9:in `<top (required)>'

Caused by:
Mysql2::Error: Duplicate entry '' for key 'index_users_on_uid'
/workspaces/hack-us-server/db/migrate/20210618033458_add_uid_unique_index_to_users.rb:5:in `change'
/workspaces/hack-us-server/bin/rails:7:in `<top (required)>'
/workspaces/hack-us-server/bin/spring:12:in `block in <top (required)>'
/workspaces/hack-us-server/bin/spring:9:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by shin-shin-01** [comment]
ローカルで実行してみましたが，エラー出ませんでした...
@bana118 立花さんはどうですか？？

**Comment by bana118** [comment]
@RenFukatsu @shin-shin-01 
自分もエラーは出ないです．uidを追加してユニークにするマイグレーションをしたので既に存在しているデータにuid要素がなくデフォルトとして空文字列がセットされuidが空文字列であるデータが複数あることになりユニークでないのでエラー，となっているんだと思います．
`rails db:migrate:reset` でdbをリセットしたら直ると思います．

**Comment by RenFukatsu** [comment]
`rails db:migrate:reset`で直りました．ありがとうございます！
